package batch.demo.mapper;

import batch.demo.model.RowData;
import batch.demo.model.Test;
import batch.demo.model.TestExample;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TestMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEST
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	long countByExample(TestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEST
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	int deleteByExample(TestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEST
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	int deleteByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEST
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	int insert(Test record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEST
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	int insertSelective(Test record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEST
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	List<Test> selectByExample(TestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEST
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	Test selectByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEST
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	int updateByExampleSelective(@Param("record") Test record, @Param("example") TestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEST
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	int updateByExample(@Param("record") Test record, @Param("example") TestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEST
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	int updateByPrimaryKeySelective(Test record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEST
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	int updateByPrimaryKey(Test record);

	List<RowData> selectByCode(@Param("code") String code);
	int updateByCode(@Param("id") String id, @Param("name") String name);
}