package batch.demo.model;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

//@Data
//@AllArgsConstructor
//@NoArgsConstructor
public class Test {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEST.ID
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEST.NAME
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEST.ID
	 * @return  the value of TEST.ID
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEST.ID
	 * @param id  the value for TEST.ID
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEST.NAME
	 * @return  the value of TEST.NAME
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEST.NAME
	 * @param name  the value for TEST.NAME
	 * @mbg.generated  Sun Nov 05 15:10:31 JST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}
}